### ISSUE TITLE
TT-120 Revision advice for Design Document - Architecture, version1

### ISSUE THREAD

**Issue by Zhuifeng414** [Capstone-Projects-2023-Spring/project-tutraffic#49]
Great job on your design document! You've provided a clear overview of the architecture of your system and included important details such as the use cases database design. Keep up the good work!

The following is some advice for further improvement.

1. To improve the user story, please provide more context by briefly describing the steps involved in each use case. This will help the reader understand the system's flow and how the user interacts.(0.5)

2. It is recommended to use a consistent notation throughout the document to improve clarity and ease of understanding. Please start each section with a number and sub-sections with sub-numbers (e.g., 1.1, 1.2). Also, label each diagram with a notation (e.g., Figure 1: Client class diagram) and provide a caption to explain the contents.(0.5)

3. Regarding the computer vision algorithm, please consider the following:(1.5)

- Will the computer vision algorithm be hosted on a Raspberry Pi or a server? This will impact the hardware requirements and processing power needed for the system.
- What type of algorithm will you choose for the computer vision component? It is important to consider factors such as accuracy, speed, and complexity when selecting an algorithm.
- Does your system process photos or videos? How will you ensure real-time processing? Please carefully consider the network delay for photo or video transfer and the processing time of the algorithm.
- Please provide a diagram to illustrate the output of your computer vision algorithm. This will help visualize the algorithm's results and make it easier for the reader to understand.

4. Please provide the class diagram for the server and the code hosted on Raspberry Pi.(1)

**Comment by loganbee** [comment]
https://capstone-projects-2023-spring.github.io/project-tutraffic/docs/system-architecture/design
